# Caskfile
install caskroom/cask/brew-cask
cask install alfred
cask install atom
# cask install arq
cask install bartender
cask install bettertouchtool
cask install firefox
cask install flux
cask install freemind
# cask install google-chrome
cask install google-drive
cask install hipchat
cask install licecap
cask install mailbox
cask install mou
cask install opera
cask install plex-home-theater
cask install spectacle

# Brewfile
install git
install git-extras
install legit
install phantomjs
install node
install ruby
